# Generated by Django 4.2.4 on 2023-10-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuhomebannermodel',
            options={'verbose_name': 'home banner', 'verbose_name_plural': 'home banners'},
        ),
    ]
