# Generated by Django 4.2.4 on 2023-12-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_menuhomebannermodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='menu_banners')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'menu banner',
                'verbose_name_plural': 'menu banners',
            },
        ),
        migrations.DeleteModel(
            name='MenuHomeBannerModel',
        ),
    ]
