# Generated by Django 4.2.4 on 2023-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactbannermodel',
            options={'verbose_name': 'contact banner', 'verbose_name_plural': 'contact banners'},
        ),
        migrations.AlterModelOptions(
            name='contactinfomodel',
            options={'verbose_name': 'contact info', 'verbose_name_plural': 'contact info'},
        ),
        migrations.AlterModelOptions(
            name='homebannermodel',
            options={'verbose_name': 'home banner', 'verbose_name_plural': 'home banners'},
        ),
        migrations.AlterModelOptions(
            name='homeintroductionmodel',
            options={'verbose_name': 'home introduction', 'verbose_name_plural': 'home introductions'},
        ),
    ]
