# Generated by Django 4.2.4 on 2023-12-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='comment_banners')),
                ('upper_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'comment banner',
                'verbose_name_plural': 'comment banners',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='user_comment_images')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.DeleteModel(
            name='HomeIntroductionModel',
        ),
    ]
