# Generated by Django 4.2.4 on 2023-12-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_commentbannermodel_commentmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(upload_to='user_comment_images')),
                ('image2', models.ImageField(upload_to='user_comment_images')),
                ('upper_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'info',
            },
        ),
    ]
