# Generated by Django 4.2.4 on 2023-12-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_homeinfomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeinfomodel',
            options={'verbose_name': 'home info', 'verbose_name_plural': 'home info'},
        ),
    ]
