# Generated by Django 4.2.4 on 2023-08-28 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_aboutbanner_aboutbannermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='client_images')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
        migrations.CreateModel(
            name='AboutInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(upload_to='about_info_images')),
                ('image2', models.ImageField(upload_to='about_info_images')),
                ('upper_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'info',
                'verbose_name_plural': 'info',
            },
        ),
        migrations.CreateModel(
            name='AboutStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='about_statistics')),
                ('stat1', models.PositiveIntegerField()),
                ('stat_title1', models.CharField(max_length=100)),
                ('stat2', models.PositiveIntegerField()),
                ('stat_title2', models.CharField(max_length=100)),
                ('stat3', models.PositiveIntegerField()),
                ('stat_title3', models.CharField(max_length=100)),
                ('stat4', models.PositiveIntegerField()),
                ('stat_title4', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='AboutTestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='about_testimonials')),
                ('upper_title', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='aboutbannermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
