# Generated by Django 4.2.4 on 2023-10-22 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_abouthomebannermodel_staffhomebannermodel_staffmodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutClientModel',
        ),
        migrations.DeleteModel(
            name='AboutTestimonialModel',
        ),
    ]
