# Generated by Django 4.2.4 on 2023-10-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_abouthomebannermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStatisticsPhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='about_statistics')),
            ],
            options={
                'verbose_name': 'statistics photo',
                'verbose_name_plural': 'statistics photos',
            },
        ),
        migrations.RemoveField(
            model_name='aboutstatisticsmodel',
            name='image',
        ),
    ]
