# Generated by Django 4.2.4 on 2023-12-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_aboutstatisticsphotomodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffhomebannermodel',
            options={'verbose_name': 'staff banner', 'verbose_name_plural': 'staff banners'},
        ),
        migrations.RenameField(
            model_name='aboutinfomodel',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='aboutinfomodel',
            name='image2',
        ),
    ]
