# Generated by Django 4.2.4 on 2023-12-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_staffhomebannermodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutHomeBannerModel',
            new_name='AboutBannerModel',
        ),
        migrations.RenameModel(
            old_name='StaffHomeBannerModel',
            new_name='StaffBannerModel',
        ),
        migrations.RenameField(
            model_name='aboutstatisticsmodel',
            old_name='stat',
            new_name='stat_number',
        ),
    ]
