# Generated by Django 4.2.4 on 2023-12-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_rename_abouthomebannermodel_aboutbannermodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbannermodel',
            name='image',
            field=models.ImageField(upload_to='about_banners'),
        ),
        migrations.AlterField(
            model_name='staffbannermodel',
            name='image',
            field=models.ImageField(upload_to='staff_banners'),
        ),
    ]
