# Generated by Django 4.2.4 on 2023-12-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='reservation_banners')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'home banner',
                'verbose_name_plural': 'home banners',
            },
        ),
    ]
