# Generated by Django 4.2.4 on 2023-12-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
